name: Build query list

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone self
      run: git clone https://github.com/${{ github.repository }} -b ${{ github.ref }}
    - name: Clone go
      run: git clone https://github.com/github/codeql-go
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Download CodeQL CLI
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "github/codeql-cli-binaries"
        version: "latest"
        file: "codeql-linux64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Unzip CodeQL CLI
      run: unzip -d cli codeql-linux64.zip
    - name: ls -R
      run: ls -R
    - name: Build query list
      run: |
        python ./codeql/misc/scripts/resolve-code-scanning-query-packs.py > output.csv
    - name: Upload query list
      uses: actions/upload-artifact@v2
      with:
        name: query-list
        path: output.csv
    
